./build/src/testAPI ../data/multi/1.txt /home/zhwang/WZH/SneakerAPI-Cpp/data/multi/slugsize1.txt &
./build/src/testAPI ../data/multi/2.txt /home/zhwang/WZH/SneakerAPI-Cpp/data/multi/slugsize2.txt &
./build/src/testAPI ../data/multi/3.txt /home/zhwang/WZH/SneakerAPI-Cpp/data/multi/slugsize3.txt &
./build/src/testAPI ../data/multi/4.txt /home/zhwang/WZH/SneakerAPI-Cpp/data/multi/slugsize4.txt &
./build/src/testAPI ../data/multi/5.txt /home/zhwang/WZH/SneakerAPI-Cpp/data/multi/slugsize5.txt &
./build/src/testAPI ../data/multi/6.txt /home/zhwang/WZH/SneakerAPI-Cpp/data/multi/slugsize6.txt &
./build/src/testAPI ../data/multi/7.txt /home/zhwang/WZH/SneakerAPI-Cpp/data/multi/slugsize7.txt &
./build/src/testAPI ../data/multi/8.txt /home/zhwang/WZH/SneakerAPI-Cpp/data/multi/slugsize8.txt &
./build/src/testAPI ../data/multi/9.txt /home/zhwang/WZH/SneakerAPI-Cpp/data/multi/slugsize9.txt &
./build/src/testAPI ../data/multi/10.txt /home/zhwang/WZH/SneakerAPI-Cpp/data/multi/slugsize10.txt &
./build/src/testAPI ../data/multi/11.txt /home/zhwang/WZH/SneakerAPI-Cpp/data/multi/slugsize11.txt &
./build/src/testAPI ../data/multi/12.txt /home/zhwang/WZH/SneakerAPI-Cpp/data/multi/slugsize12.txt &
./build/src/testAPI ../data/multi/13.txt /home/zhwang/WZH/SneakerAPI-Cpp/data/multi/slugsize13.txt &
./build/src/testAPI ../data/multi/14.txt /home/zhwang/WZH/SneakerAPI-Cpp/data/multi/slugsize14.txt &
./build/src/testAPI ../data/multi/15.txt /home/zhwang/WZH/SneakerAPI-Cpp/data/multi/slugsize15.txt &
./build/src/testAPI ../data/multi/16.txt /home/zhwang/WZH/SneakerAPI-Cpp/data/multi/slugsize16.txt &
./build/src/testAPI ../data/multi/17.txt /home/zhwang/WZH/SneakerAPI-Cpp/data/multi/slugsize17.txt &
./build/src/testAPI ../data/multi/18.txt /home/zhwang/WZH/SneakerAPI-Cpp/data/multi/slugsize18.txt &
./build/src/testAPI ../data/multi/19.txt /home/zhwang/WZH/SneakerAPI-Cpp/data/multi/slugsize19.txt &
./build/src/testAPI ../data/multi/20.txt /home/zhwang/WZH/SneakerAPI-Cpp/data/multi/slugsize20.txt
